Review development
SolarMC-Dev/SolarCreditsPlugin pull request #1
Opened 2021-05-11 05:11 UTC by Zone-Infinity

2021-05-11 05:15 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +        X_TEBEX_SECRET = plugin.getConfig().getString("tebex.secret");
Preinitialize this somewhere else and then pass it here.

2021-05-11 05:15 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +public class CreditCommands implements CommandExecutor {
I recommend subdividing the logic here into many subclasses for readability and OOP - Furthermore, an official SolarMC command framework known as Branch is in development right now by me - when it is done i can show you how to implement it.

2021-05-11 05:17 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +        if (args.length == 1) {
This is a prime of example of why to use a command framework or at least switch to a subcommand-like class structure - this is messy and everything is stringly typed

2021-05-11 05:19 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +                                        if (X_TEBEX_SECRET == null) {
Preinitializing this variable will mean no nullity checks as it is guaranteed by whatever class preinitializes it. Something as important as your tebex api secret to plugin functionality shouldn't be null at any point.

2021-05-11 05:26 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +                Player receiver = plugin.getServer().getPlayerExact(playerName);
Pretty sure the solar api can do this as well but return an optional so you don't have to do an explicit null check, but that's up to you.

2021-05-11 05:27 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +                } else if (subCommand.equalsIgnoreCase("add")) { // credits add <> <>
These need permission checks otherwise normal players can give themselves free credits

2021-05-11 05:32 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +                                // receiver.getSolarPlayer().getData(CreditsKey.INSTANCE).setBalance(transaction, BigDecimal.valueOf(amount));
implement

2021-05-11 05:34 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/DataManager.java
> +        saveDefaultConfig();
You can probably use dazzleconf for all of this

2021-05-11 05:34 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/RotatingItem.java
> +public record RotatingItem(String name, Material material, double priceInCredits,
Yeay, records!

2021-05-11 05:36 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/menus/ConfirmMenu.java
> +        for (int i = 0; i < confirmMenu.getDimensions().getArea(); i++) {
You can use canvas's Mask feature for this instead of iterating: look at the docs and the wiki!

2021-05-11 05:36 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/menus/RotatingShopMenu.java
> +        for (int i = 0; i < items.length; i++) {
Same story here, use masks for this.

2021-05-11 05:36 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/menus/RotatingShopMenu.java
> +        balMeta.setDisplayName(ChatColor.BOLD + "" + ChatColor.RED + "Balance : " + credits);
I think ariel wants stuff like this to be configurable

2021-05-11 05:38 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/menus/RotatingShopMenu.java
> +        loadItems();
A248 is picky about code in the constructor rules, i will also be so: It's just better practice to let constructors only be used for class _construction_ - you can easily do all of these things here outside of the class and pass as variables. Furthermore, that PlayerInteracted stuff is a bad idea

2021-05-11 05:39 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/menus/RotatingShopMenu.java
> +        loadItems();
After player has bought the item , they can't buy it again  as Ariel said, so I used that , tell me if there is better idea 😅

I'll make a Builder of Rotating shop

2021-05-11 05:40 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/menus/RotatingShopMenu.java
> +    public void loadItems() {
Not something that the menu should do is interact with configs - move this to your config class!

2021-05-11 05:41 UTC, auriium requested changes
Finished review!

2021-05-11 05:42 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/menus/RotatingShopMenu.java
> +        loadItems();
The idea is still a good one in practice but that isn't what i'm critiquing here, i'm critiquing the implementation which uses this code in the constructor.

2021-05-15 04:28 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/config/ConfigManager.java
> +    private volatile C configData;
Why is this marked as volatile? are you modifying this threadedly?

2021-05-15 04:30 UTC, auriium approved these changes

2021-05-15 04:30 UTC, auriium commented
Desired review from @A248

2021-05-15 04:38 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/config/ConfigManager.java
> +    private volatile C configData;
Nope , should I remove it , I just got the manager from the examples...

2021-05-15 19:26 UTC, A248 commented on plugin.yml
> +version: 1.0
```suggestion
version: ${project.version}
```
I suggest using this variable and enabling resource filtering so that the version is automatically set at build-time.

2021-05-15 19:26 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +    public CreditCommands(SolarCredit plugin, @NotNull String TebexSecret) {
```suggestion
    public CreditCommands(SolarCredit plugin, String TebexSecret) {
```
I recommend using a nonnull-by-default policy. Most tools have the possibility to configure this. It's the way Aesthetik and I develop - never null unless documented otherwise.

2021-05-15 19:26 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +                        plugin.reloadConfig();
You'll need to do a little more than just this, as I think you've seen

2021-05-15 19:26 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +                            + player.getSolarPlayer().getData(CreditsKey.INSTANCE).currentBalance().floatValue());
There are better ways to format a BigDecimal than Float.toString. For example https://stackoverflow.com/a/31531227

2021-05-15 19:26 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +                                                createGiftCard(player, amount, giftCardCode -> player.sendMessage(ChatColor.translateAlternateColorCodes('&', "&aGift Card Code : &r&l&6" + giftCardCod
I'm not sure if you are aware that you are keeping the transaction open during the HTTP request, considering you catch any IOExceptions in `createGiftCard`. Let me explain why this is relevant.

Normally, if you had a heavy operation like a HTTP request, you would want to close the transaction before performing the heavy operation. That way, you relinquish the connection back to the pool and other threads can make use of the connection pool. While the HTTP request occurs, you aren't using the connection, so you let others use that connection.

However, here, we have a case where we need to ensure reliable transactional consistency. The closest way to achieve that here is by running the HTTP request inside the transaction. If the HTTP request fails, the transaction also fails - which is what we want. We never want the transaction to succeed but the HTTP request to fail, or vice-versa. So, it is justified to run the HTTP request inside the transaction because correctness is more important than performance.

Yet, in the `createGiftCard` method, you are catching IOExceptions occurring from the HTTP request. So if the HTTP request fails with an IOException, it will not cancel the transaction in this code, here. To solve this, you should re-throw the IOException instead of catching and logging it. Rethrowing the exception will cause the transaction to also fail.

2021-05-15 19:26 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +                double amount = Double.parseDouble(amountString);
Minor note: this is parsing the amount twice, which is not a huge deal. It's more about code quality to not repeat the same operation if you can.

2021-05-15 19:26 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +                sender.sendMessage("Sorry, but " + amountString + " is not a double!");
```suggestion
                sender.sendMessage("Sorry, but " + amountString + " is not a number!");
```
If only everyone understand what a double was.

2021-05-15 19:26 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +    public void createGiftCard(CommandSender sender, double amount, /*String expiresAt,*/ Consumer<String> giftCardCode) {
Does this need to be public?

2021-05-15 19:26 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +    public boolean onCommand(CommandSender sender, Command arg1, String arg2, String[] args) {
This is a very large method. I suggest breaking it up into smaller methods or classes.

2021-05-15 19:26 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +    public boolean isNumberCorrectly(String strNum) {
```suggestion
    private boolean isValidNumber(String strNum) {
```

2021-05-15 19:26 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/RotatingItem.java
> +    public String getName() {
You don't need to write any of these getters - the record generates them as `name()`, `material()`, `priceInCredits`. You can use those without writing any extra code.

2021-05-15 19:26 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/RotatingItem.java
> +                           List<String> lore) {
To preserve the immutability of a record, mutable collections should be turned into immutable copies. For a List, you would use List.copyOf:
```java
this.lore = List.copyOf(lore);
```

2021-05-15 19:26 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/config/ConfigManager.java
> +    private volatile C configData;
Having it volatile makes the entire ConfigManager thread-safe due to the way the field is atomically used. This is pretty useful because it lets you reload asynchronously without any extra effort.

If you don't reload asynchronously then you don't need to mark it volatile.

2021-05-15 19:26 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/menus/RotatingShopMenu.java
> +    public RotatingItem[] getItems() {
I suggest writing a simple unit test for this, simply to double-check that it works as intended.

2021-05-16 08:41 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/menus/RotatingShopMenu.java
> +    public RotatingItem[] getItems() {
I have made a test for that - [Config Test](https://github.com/SolarMC-Dev/SolarCreditsPlugin/blob/main/src/test/java/gg/solarmc/solarcredits/ConfigTest.java)

2021-05-16 09:26 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/RotatingItem.java
> +                           List<String> lore) {
lore is a final variable , so we cant assign it again 
so it's immutable

2021-05-17 12:31 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +                                                createGiftCard(player, amount, giftCardCode -> player.sendMessage(ChatColor.translateAlternateColorCodes('&', "&aGift Card Code : &r&l&6" + giftCardCod
Yes, i got it 
but I am making the request in the `runTransact`  and it tells me to catch the IOException cause it's thrown 😕

2021-05-17 13:12 UTC, Zone-Infinity commented
I need a review for this big commit is Auriium still busy ? or should I ask A248

2021-05-17 13:35 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/RotatingItem.java
> +                           List<String> lore) {
final and immutable are not the same thing. For example, you can have:
```java
private final List<String> lore = new ArrayList<>();
```
The List is final so it cannot be re-assigned. However, it is mutable because its contents can be modified.

Regarding this particular situation:
A record can decide its contents at construction. You can use the [canonical record constructor](https://openjdk.java.net/jeps/395) to achieve this:
```
public record RotatingItem(String name, Material material, double priceInCredits, String command, String message, String displayName, List<String> lore) {

  RotatingItem {
    lore = List.copyOf(lore);
  }
}
```

2021-05-17 13:36 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +                                                createGiftCard(player, amount, giftCardCode -> player.sendMessage(ChatColor.translateAlternateColorCodes('&', "&aGift Card Code : &r&l&6" + giftCardCod
IOException is a checked exception, which means it cannot escape methods which are not declared to throw it.

If you re-throw it in an UncheckedIOException you accomplish all your goals:
```java
try {
  // ...
} catch (IOException ex) {
  throw new UncheckedIOException("Failed to create gift card with tebex web api", ex);
}
```

2021-05-17 13:37 UTC, A248 commented
I'll be able to complete another full review later this afternoon. (Edit: afternoon for me, ~ 6 hours from now for everyone else)

2021-05-17 13:38 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/RotatingItem.java
> +                           List<String> lore) {
ah ok , got it

2021-05-18 01:38 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +    public CreditCommands(SolarCredit plugin, String TebexSecret) {
```suggestion
    public CreditCommands(SolarCredit plugin, String tebexSecret) {
```

2021-05-18 01:38 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/CreditCommands.java
> +        return false;
Always `return true` from an implementation of onCommand. Returning false sends the usage in the plugin.yml

2021-05-18 01:38 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/SolarCredit.java
> +    private String TEBEX_SECRET;
This field can be made into a local variable

2021-05-18 01:38 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/command/CommandHelper.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(CreditCommands.class);
Mismatched logger class. I suggest using copy-and-paste-proof logger initialization which uses the caller class:
```java
private static final Logger LOGGER = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());
```
Or if, like me, you prefer not to abuse MethodHandles.lookup(), there's ThisClass.get() from a dependency of the solar api:
```java
private static final Logger LOGGER = LoggerFactory.getLogger(ThisClass.get());
```

2021-05-18 01:38 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/command/CommandHelper.java
> +    private static final DecimalFormat df = new DecimalFormat("#,###.00");
DecimalFormat is not thread safe, so usually avoid re-using it inside a field. In this case it's fine because all of Bukkit is single-threaded.

2021-05-18 01:38 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/command/CommandHelper.java
> +        } catch (NumberFormatException | NullPointerException e) {
Never catch NullPointerException

2021-05-18 01:38 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/command/CreditSubCommand.java
> +    DecimalFormat df = new DecimalFormat("#,###.00");
Fields like these don't belong in an interface.

2021-05-18 01:38 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/command/commands/AddCommand.java
> +        return true;
If the user doesn't have the permission, they should receive a no-permission message.

2021-05-18 01:38 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/command/commands/SpendCommand.java
> +public record SpendCommand(SolarCredit plugin, String X_TEBEX_SECRET) implements CreditSubCommand {
```suggestion
public record SpendCommand(SolarCredit plugin, String tebexSecret) implements CreditSubCommand {
```
In general, fields should always be lowerCamelCase. Reserve UPPER_SNAKE_CASE for constants

2021-05-18 01:38 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/command/commands/SpendCommand.java
> +    private void createGiftCard(CommandSender sender, double amount, Consumer<String> giftCardCode) {
```suggestion
    private void createGiftCard(Player sender, double amount, Consumer<String> giftCardCode) {
```
So you can remove the useless cast

2021-05-18 01:38 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/config/ConfigManager.java
> +            System.err.println("The yaml syntax in your configuration is invalid. "
Although this is the example provided in the documentation, in actual code, you almost never want to use `System.err`.

The admins are competent enough that they can handle us re-throwing the exception:
```java
} catch (ConfigFormatSyntaxException | InvalidConfigException ex) {
  throw new RuntimeException("Invalid config or config syntax. Please fix it and reload the config", ex);
}
```

2021-05-18 01:39 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/menus/RotatingShopMenu.java
> +    public RotatingItem[] getItems() {
I see the test for the configuration that you made.

However, you do not have a test which calls `getItems()`. You can add another test method which calls getItems and verifies that the right items are returned.

2021-05-18 02:00 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/menus/RotatingShopMenu.java
> +    public RotatingItem[] getItems() {
If u mean `items()` it's already called when i call `loadItems()` and then for getting the items `getRotatingItems()`
i dont see a `getItems()` nor i have used it anywhere 🤔

2021-05-18 02:04 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/command/CommandHelper.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(CreditCommands.class);
I used that bcz i wanted to log from `CreditCommands` class , but ok if u want me to do this 

thought i have never used `lookup()`

ah i got it why you used these methods.

2021-05-18 02:05 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/command/CommandHelper.java
> +    private static final DecimalFormat df = new DecimalFormat("#,###.00");
oh ok , so if the program is not single-threaded , should i define it in the method where i use it ?

2021-05-18 02:14 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/command/CommandHelper.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(CreditCommands.class);
Or, use private final Logger LOGGER = LoggerFactory.getLogger(getClass()) and simply don't rely on it being static...? Completely copyproof with no abuse or reflection!

2021-05-18 02:14 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/command/CommandHelper.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(CreditCommands.class);
What is ThisClass.get() from?

2021-05-18 02:16 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/command/CommandHelper.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(CreditCommands.class);
`space.arim.obnibus.util`

2021-05-18 02:17 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/command/CommandHelper.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(CreditCommands.class);
> Or, use private final Logger LOGGER = LoggerFactory.getLogger(getClass()) and simply don't rely on it being static...? Completely copyproof with no abuse or reflection!

The reason it is static , cause the class is a record 😅 
and records cant have instance field , should I change it to class ?

2021-05-18 13:56 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/menus/RotatingShopMenu.java
> +        for (int i = 0; i < items.length; i++) {
Is there any way to use masks for click handling too ?
so that i can use them here

2021-05-19 20:46 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/command/CommandHelper.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(CreditCommands.class);
Oh, forgot it was a record haha! probably fine to do what a248 suggested then

2021-05-20 11:51 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/menus/RotatingShopMenu.java
> +        balMeta.setDisplayName(ChatColor.BOLD + "" + ChatColor.RED + "Balance : " + credits);
The map stuff or something else ?

2021-05-20 18:46 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/command/CommandHelper.java
> +    private static final DecimalFormat df = new DecimalFormat("#,###.00");
Yes. Here it doesn't matter though, so it's all fine.

2021-06-30 16:37 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/SolarCredit.java
> +    private Config config;
Why can't this be a local var?

2021-06-30 16:37 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/SolarCredit.java
> +    private Config config;
Oh, reloading. Fair enough.

2021-06-30 16:37 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/command/CommandHelper.java
> +                    sender.sendMessage(ChatColor.RED + "Sorry, but i'm not able to find the player " + playerName + " !");
If you wanted you could do a message config

2021-06-30 16:40 UTC, auriium approved these changes

2021-06-30 16:42 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/command/CommandHelper.java
> +                    sender.sendMessage(ChatColor.RED + "Sorry, but i'm not able to find the player " + playerName + " !");
Oh , I'll do it 👍

2021-07-06 02:21 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/SolarCredit.java
> +            getServer().getPluginManager().disablePlugin(this);
Ugh, I'd rather not have to use PAPI while testing. Do you think you could make it optional?

2021-07-06 02:23 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/SolarCredit.java
> +            getServer().getPluginManager().disablePlugin(this);
Ariel explicitly stated he wanted PAPI i'm pretty sure, unless we have a working alternative that provides similar functionality

2021-07-06 02:23 UTC, auriium commented on src/main/java/gg/solarmc/solarcredits/SolarCredit.java
> +            getServer().getPluginManager().disablePlugin(this);
I do believe you said you were working on starting such a project but until you can get around to it don't you think PAPI is an acceptable stopgap?

2021-07-06 02:24 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/SolarCredit.java
> +            getServer().getPluginManager().disablePlugin(this);
He wanted papi for the Scoreboard only

2021-07-06 02:25 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/SolarCredit.java
> +            getServer().getPluginManager().disablePlugin(this);
should I still make it optional then ? 
and We have papi on our server , right ?

2021-07-06 19:00 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/SolarCredit.java
> +            getServer().getPluginManager().disablePlugin(this);
PAPI is fine for now, yes. I was talking about my personal testing - I'd rather not have to use PAPI, but I guess it's unavoidable.

2021-07-19 16:15 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/SolarCredit.java
> +        } catch (FileAlreadyExistsException ignored) {
If you're checking for the existence of the file with `backupFile.exists()`, why are you catching this exception?

Also, for new code, you should prefer java.nio.file.Path rather than the clunky and limited java.io.File

2021-07-19 16:18 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/SolarCredit.java
> +                fout.write(c);
There's no reason to use manually buffering and writing anymore (reading single characters is not very efficient either). You should use inputStream.transferTo(outputStream) or fileChannel.transferFrom(readableByteChannel)

2021-07-19 16:23 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/SolarCredit.java
> +        } catch (FileAlreadyExistsException ignored) {
How do i use Path for backupFile ? it doesn't exist yet

2021-07-19 16:26 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/SolarCredit.java
> +        } catch (FileAlreadyExistsException ignored) {
You use Path the same way you use File. The actual file doesn't need to exist in order for the object to exist.

2021-07-19 16:38 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/SolarCredit.java
> +                fout.write(c);
```java
Path dataFolder = getDataFolder().toPath();
Path backupFile = Path.of(dataFolder.toString(), backupFilePath);

FileInputStream fileInputStream = new FileInputStream(dataFolder.resolve(filePath).toFile());
FileOutputStream fileOutputStream = new FileOutputStream(backupFile.toFile());

fileInputStream.transferTo(fileOutputStream);
LOGGER.info("rotatingShop backup Complete!");```
I guess i shouldn't use Path in this case and directly put that in streams consutrctor
Is this enough ?? also Does FileOutputStream create the file , internet told me `yes` but the docs told me `throws exception`

2021-07-19 16:49 UTC, A248 commented on src/main/java/gg/solarmc/solarcredits/SolarCredit.java
> +                fout.write(c);
Never open closable resources outside the scope of a try-with-resources block.

>  also Does FileOutputStream create the file 

With Path and FileChannel, you don't have to worry about this, because it's abundantly clear that StandardOpenOption.CREATE will create the file:

```java
try (ReadableByteChannel sourceChannel = FileChannel.open(sourceFile, StandardOpenOption.READ);
    FileChannel targetChannel = FileChannel.open(targetFile, StandardOpenOption.CREATE, StandardOpenOption.WRITE)) {
  targetChannel.transferFrom(sourceChannel, 0, Long.MAX_VALUE);
}
```

The answer to your question, literally, is yes.

> internet told me yes but the docs told me throws exception

Throwing an exception doesn't mean it doesn't create the file.

2021-07-19 16:51 UTC, Zone-Infinity commented on src/main/java/gg/solarmc/solarcredits/SolarCredit.java
> +                fout.write(c);
oh ok

2021-08-05 14:34 UTC, merged